name: OMVServerAdmin

options:
  bundleIdPrefix: com.omvadmin
  deploymentTarget:
    iOS: "16.0"

settings:
  SWIFT_VERSION: "5.9"

targets:
  OMVServerAdmin:
    type: application
    platform: iOS
    sources:
      - OMVServerAdmin
    info:
      path: OMVServerAdmin/Info.plist
      properties:
        CFBundleDisplayName: OMV Admin
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: OMVServerAdmin/OMVServerAdmin.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.omvadmin.app
      INFOPLIST_FILE: OMVServerAdmin/Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      TARGETED_DEVICE_FAMILY: "1,2"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
    scheme:
      testTargets: []
      gatherCoverageData: false
